//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyWaterCarrier.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HappyWaterCarrierEntities : DbContext
    {
        public HappyWaterCarrierEntities()
            : base("name=HappyWaterCarrierEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Заказ> Заказ { get; set; }
        public virtual DbSet<Подразделение> Подразделение { get; set; }
        public virtual DbSet<Пол> Пол { get; set; }
        public virtual DbSet<Сотрудник> Сотрудник { get; set; }
    }
}
