//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyWaterCarrier.Database
{
    using HappyWaterCarrier.Classes;
    using HappyWaterCarrier.Pages.Orders;
    using System;
    using System.Collections.Generic;
    using PropertyChanged;
    [AddINotifyPropertyChangedInterface]
    public partial class Заказ
    {
        public int Id { get; set; }
        public Nullable<int> Номер { get; set; }
        public string Название_товара { get; set; }
        public Nullable<int> Сотрудник_Id { get; set; }
    
        public virtual Сотрудник Сотрудник { get; set; }

        
    }
}
