//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyWaterCarrier.Database
{
    using HappyWaterCarrier.Classes;
    using HappyWaterCarrier.Pages.Divisions;
    using PropertyChanged;
    using System;
    using System.Collections.Generic;

    [AddINotifyPropertyChangedInterface]    
    public partial class Подразделение
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Подразделение()
        {
            this.Сотрудник1 = new HashSet<Сотрудник>();
        }
    
        public int Id { get; set; }
        public string Название { get; set; }
        public Nullable<int> Руководитель_Id { get; set; }
    
        public virtual Сотрудник Сотрудник { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Сотрудник> Сотрудник1 { get; set; }
    }
}
