//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyWaterCarrier.Database
{
    using HappyWaterCarrier.Classes;
    using HappyWaterCarrier.Pages.Employees;
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудник
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Сотрудник()
        {
            this.Заказ = new HashSet<Заказ>();
            this.Подразделение = new HashSet<Подразделение>();
        }
    
        public int Id { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public Nullable<System.DateTime> Дата_рождения { get; set; }
        public string DateOfBirthAsString { get { return Дата_рождения.Value.ToShortDateString(); } set { } }
        public Nullable<int> Пол_Id { get; set; }
        public Nullable<int> Подразделение_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заказ> Заказ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Подразделение> Подразделение { get; set; }
        public virtual Подразделение Подразделение1 { get; set; }
        public virtual Пол Пол { get; set; }
        
    }
}
